### ISSUE TITLE
Stream has already been listened to after 2.0.1

### ISSUE THREAD

**Issue by soufianebenyaala** [pratikbaid3/flutter_client_sse#29]
flutter : 3.24.0
In the app, I have one screen calling SSEClient.subscribeToSSE, when logout the stream must stop but still work. when try to login again. I am getting the following exception: 

 
```════════ Exception caught by widgets library ═══════════════════════════════════
The following StateError was thrown building Builder:
Bad state: Stream has already been listened to.

The relevant error-causing widget was:
    MaterialApp MaterialApp:file:///home/sofiene/flutter_projects/questmobileapp/lib/quest_app.dart:142:28

When the exception was thrown, this was the stack:
#3      _QuestMainLayoutState.listener (package:quest/features/quest_main_layout/presentation/quest_main_layout.dart:37:14)
quest_main_layout.dart:37
#4      _QuestMainLayoutState.initState (package:quest/features/quest_main_layout/presentation/quest_main_layout.dart:51:5)
quest_main_layout.dart:51
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5748:55)
framework.dart:5748
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593:5)
framework.dart:5593
...     Normal element mounting (228 frames)
```

code : 
```
 listener() {
      SSEClient.subscribeToSSE(
          method: SSERequestType.GET,
          url: '************/push-notifications/listen',
          header: {
            "Authorization": ***************,
            "Accept": "text/event-stream",
            "Cache-Control": "no-cache",
          }).listen((event) {
        PushNotificationUtil.eventHandler(
          event: event,
          context: context,
        );
      });
    
    TimerService().startTimer(listener);
  }
  @override
  void initState() {
    listener();
    super.initState();
  }

 
```

when logout : 

```
void onLogout(){
                     SSEClient.unsubscribeFromSSE();
                      TimerService().stopTimer();
                      Navigator.pushNamedAndRemoveUntil(
                        context,
                        AppRouteName.login,
                        (Route<dynamic> route) => false,
                      );
}
```

**Comment by pratikbaid3** [comment]
https://github.com/pratikbaid3/flutter_client_sse/pull/32
@pedroculque @soufianebenyaala I have created a fix for this. It will be helpful if you could try it out to confirm it it fits your use case. Thanks
